// <auto-generated />
using System;
using Formula1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Formula1.Migrations
{
    [DbContext(typeof(FormulaContext))]
    [Migration("20210427104420_“DriversCircuits”")]
    partial class DriversCircuits
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Formula1.Models.Circuits", b =>
                {
                    b.Property<Guid>("CircuitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CircuitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CircuitId");

                    b.ToTable("Circuits");

                    b.HasData(
                        new
                        {
                            CircuitId = new Guid("30d27578-80ab-4dd6-b2aa-a4e7e37067c2"),
                            CircuitName = "Albert Park",
                            Country = "Australia",
                            Url = "https://f1-circuits.nl/albert-park/"
                        },
                        new
                        {
                            CircuitId = new Guid("81d30bc3-427c-4058-b4eb-d114353f8da7"),
                            CircuitName = "Shanghai International Circuit",
                            Country = "China",
                            Url = "https://f1-circuits.nl/shanghai/"
                        },
                        new
                        {
                            CircuitId = new Guid("5b70c730-20bc-4662-af31-7379a4cd1dae"),
                            CircuitName = "Bahrain International Circuit",
                            Country = "Bahrain",
                            Url = "https://f1-circuits.nl/bahrain/"
                        },
                        new
                        {
                            CircuitId = new Guid("a138150b-559e-46be-90f4-7220782f9a3d"),
                            CircuitName = "Sochi Autodrom",
                            Country = "Russia",
                            Url = "https://f1-circuits.nl/sochi/"
                        },
                        new
                        {
                            CircuitId = new Guid("f70f11f4-0495-47c7-bbbb-42b0ecd3ada8"),
                            CircuitName = "Circuit de Barcelona-Catalunya",
                            Country = "Spain",
                            Url = "https://f1-circuits.nl/barcelona/"
                        },
                        new
                        {
                            CircuitId = new Guid("12c84d29-3c5b-49a7-99aa-d90b75f3bf87"),
                            CircuitName = "Circuit de Monaco",
                            Country = "Monaco",
                            Url = "https://f1-circuits.nl/monaco/"
                        },
                        new
                        {
                            CircuitId = new Guid("2695c543-821b-4e6b-b868-bb58e3126667"),
                            CircuitName = "Circuit Gilles Villeneuve",
                            Country = "Canada",
                            Url = "https://f1-circuits.nl/gilles-villeneuve/"
                        },
                        new
                        {
                            CircuitId = new Guid("ac690c2e-ff94-4057-a5aa-2c596c191637"),
                            CircuitName = "Baku City Circuit",
                            Country = "Azerbeidzjan",
                            Url = "https://f1-circuits.nl/baku/"
                        },
                        new
                        {
                            CircuitId = new Guid("0c2360d7-9983-41e1-88e9-25e3af946d72"),
                            CircuitName = "Red Bull Ring",
                            Country = "Austria",
                            Url = "https://f1-circuits.nl/red-bull-ring/"
                        },
                        new
                        {
                            CircuitId = new Guid("91af9a94-b0b9-48f7-9d65-f392c4a7345f"),
                            CircuitName = "Silverstone",
                            Country = "United Kingdom",
                            Url = "https://f1-circuits.nl/silverstone/"
                        },
                        new
                        {
                            CircuitId = new Guid("1e62e8d2-1ccc-4a83-b3a6-2c7c5d23c496"),
                            CircuitName = "Hungaroring",
                            Country = "Hungary",
                            Url = "https://f1-circuits.nl/hungaroring/"
                        },
                        new
                        {
                            CircuitId = new Guid("f3b73575-8e11-4cee-b70f-4d2721d5346e"),
                            CircuitName = "Circuit Spa-Francorchamps",
                            Country = "Belgium",
                            Url = "https://f1-circuits.nl/spa-francorchamps/"
                        },
                        new
                        {
                            CircuitId = new Guid("10003dc5-4c58-4d04-8c5d-044d3f12b337"),
                            CircuitName = "Autodromo Nazionale Monza",
                            Country = "Italy",
                            Url = "https://f1-circuits.nl/monza/"
                        },
                        new
                        {
                            CircuitId = new Guid("7fe4f380-e76d-4975-84f0-eb74fcb74535"),
                            CircuitName = "Marina Bay Circuit",
                            Country = "Singapore",
                            Url = "https://f1-circuits.nl/marina-bay/"
                        },
                        new
                        {
                            CircuitId = new Guid("49397597-d529-48e7-9421-f7a1d86a1fc6"),
                            CircuitName = "Sepang International Circuit",
                            Country = "Malaysia",
                            Url = "https://f1-circuits.nl/sepang/"
                        },
                        new
                        {
                            CircuitId = new Guid("c5ebd482-54a0-4936-9543-9768a3828040"),
                            CircuitName = "Suzuka",
                            Country = "Japan",
                            Url = "https://f1-circuits.nl/suzuka/"
                        },
                        new
                        {
                            CircuitId = new Guid("9a04ab33-1482-458b-8040-96ee9b97ea69"),
                            CircuitName = "Autódromo Hermanos Rodríguez",
                            Country = "Mexico",
                            Url = "https://f1-circuits.nl/mexico/"
                        },
                        new
                        {
                            CircuitId = new Guid("9db91460-c226-4016-9e04-4dc6321d92d8"),
                            CircuitName = "Circuit of the Americas",
                            Country = "United States",
                            Url = "https://f1-circuits.nl/americas/"
                        },
                        new
                        {
                            CircuitId = new Guid("5fbe7fe7-e38b-4f0e-8a73-3b851a31ea77"),
                            CircuitName = "Interlagos",
                            Country = "Brazil",
                            Url = "https://f1-circuits.nl/interlagos/"
                        },
                        new
                        {
                            CircuitId = new Guid("d1d6b362-fc91-4830-a53c-61c0b0970f27"),
                            CircuitName = "Yas Marina Circuit",
                            Country = "United Arab Emirates",
                            Url = "https://f1-circuits.nl/yas-marina/"
                        },
                        new
                        {
                            CircuitId = new Guid("ccbf4c6d-a58e-43d1-9d7b-eb843c235cb7"),
                            CircuitName = "Paul Ricard",
                            Country = "France",
                            Url = "https://f1-circuits.nl/paul-ricard/"
                        },
                        new
                        {
                            CircuitId = new Guid("9e049ec8-c5c8-4ca8-a3b9-1e1d1951a6c5"),
                            CircuitName = "Hockendheimring",
                            Country = "Germany",
                            Url = "https://f1-circuits.nl/hockenheim/"
                        },
                        new
                        {
                            CircuitId = new Guid("511b3610-3e58-41ec-8e25-42690ef70d0c"),
                            CircuitName = "Zandvoort",
                            Country = "The Netherlands",
                            Url = "https://f1-circuits.nl/zandvoort/"
                        },
                        new
                        {
                            CircuitId = new Guid("a2d70a92-780b-4b41-a95f-dd80cbd60eee"),
                            CircuitName = "Vietnam",
                            Country = "Vietnam",
                            Url = "https://f1-circuits.nl/vietnam/"
                        },
                        new
                        {
                            CircuitId = new Guid("e319e422-61ce-482a-956c-b44a547dc8a6"),
                            CircuitName = "Mugello Circuit",
                            Country = "Italy",
                            Url = "https://f1-circuits.nl/mugello/"
                        },
                        new
                        {
                            CircuitId = new Guid("5a67f641-38ea-42c7-8f18-0a99a6a6c9b1"),
                            CircuitName = "Nürburging",
                            Country = "Germany",
                            Url = "https://f1-circuits.nl/nurburgring/"
                        },
                        new
                        {
                            CircuitId = new Guid("caea5ed3-0c3c-4a64-9af7-c9219387b859"),
                            CircuitName = "Autodromo Enzo e Dino Ferrari",
                            Country = "Italy",
                            Url = "https://f1-circuits.nl/imola/"
                        },
                        new
                        {
                            CircuitId = new Guid("3f4c06c5-359e-4eb4-96ad-ad71ea192389"),
                            CircuitName = "Autodromo Internacional do Algarve",
                            Country = "Portugal",
                            Url = "https://f1-circuits.nl/algarve/"
                        },
                        new
                        {
                            CircuitId = new Guid("f2a417d5-317d-49bb-9922-2985b66381cb"),
                            CircuitName = "Istanbul Park",
                            Country = "Turkey",
                            Url = "https://f1-circuits.nl/istanbul-park/"
                        },
                        new
                        {
                            CircuitId = new Guid("aa512f0b-ed92-4407-8d74-cfefccc1af2b"),
                            CircuitName = "Jeddah Street Circuit",
                            Country = "Saudi Arabia",
                            Url = "https://f1-circuits.nl/jeddah-street/"
                        });
                });

            modelBuilder.Entity("Formula1.Models.DriverCircuits", b =>
                {
                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("CircuitId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("CircuitsCircuitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DriverId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DriverId", "CircuitId");

                    b.HasIndex("CircuitsCircuitId");

                    b.HasIndex("DriverId1");

                    b.ToTable("DriverCircuits");
                });

            modelBuilder.Entity("Formula1.Models.Drivers", b =>
                {
                    b.Property<Guid>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Team")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriverId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            DriverId = new Guid("c565a83a-8b50-4897-bed6-8aa76092e02d"),
                            Age = 23,
                            Country = "Netherlands",
                            DriverName = "Max Verstappen",
                            Number = 33,
                            Team = "Red Bull Racing"
                        },
                        new
                        {
                            DriverId = new Guid("1128f6f3-e6ae-4540-9a82-837a2afd7b01"),
                            Age = 31,
                            Country = "Mexico",
                            DriverName = "Sergio Perez",
                            Number = 11,
                            Team = "Red Bull Racing"
                        },
                        new
                        {
                            DriverId = new Guid("ce446f88-41d6-4c47-af0a-5a9b4f35e094"),
                            Age = 26,
                            Country = "Spain",
                            DriverName = "Carlos Sainz",
                            Number = 55,
                            Team = "Ferrari"
                        },
                        new
                        {
                            DriverId = new Guid("2c502b0d-a503-4525-81b5-da75dccf4742"),
                            Age = 23,
                            Country = "Monaco",
                            DriverName = "Charles Leclerc",
                            Number = 16,
                            Team = "Ferrari"
                        },
                        new
                        {
                            DriverId = new Guid("2203e0df-1e73-49e8-8c89-cd19cf184144"),
                            Age = 21,
                            Country = "United Kingdom",
                            DriverName = "Lando Norris",
                            Number = 4,
                            Team = "McLaren"
                        },
                        new
                        {
                            DriverId = new Guid("c541e9f9-5f17-4997-9790-fe68ac280b4c"),
                            Age = 31,
                            Country = "Australia",
                            DriverName = "Daniel Ricciardo",
                            Number = 3,
                            Team = "McLaren"
                        },
                        new
                        {
                            DriverId = new Guid("cb2246c8-9a2c-4665-b1fb-438f87098db4"),
                            Age = 36,
                            Country = "United Kingdom",
                            DriverName = "Lewis Hamilton",
                            Number = 44,
                            Team = "Mercedes"
                        },
                        new
                        {
                            DriverId = new Guid("90578227-a01b-438f-b8bd-92a0082505e4"),
                            Age = 31,
                            Country = "Finland",
                            DriverName = "Valtteri Bottas",
                            Number = 77,
                            Team = "Mercedes"
                        },
                        new
                        {
                            DriverId = new Guid("5c133061-ba22-4679-ab9f-38427995c13d"),
                            Age = 25,
                            Country = "France",
                            DriverName = "Pierre Gasly",
                            Number = 10,
                            Team = "AlphaTauri"
                        },
                        new
                        {
                            DriverId = new Guid("0c63198e-7daf-4a2d-b3b0-572f7fd2f915"),
                            Age = 20,
                            Country = "Japan",
                            DriverName = "Yuki Tsunoda",
                            Number = 22,
                            Team = "AlphaTauri"
                        },
                        new
                        {
                            DriverId = new Guid("92a68204-818b-41dd-b25a-8b569faddb3c"),
                            Age = 25,
                            Country = "France",
                            DriverName = "Lance Stroll",
                            Number = 18,
                            Team = "Aston Martin"
                        },
                        new
                        {
                            DriverId = new Guid("cc5e055a-f2ff-4adc-be1d-ce7d79e6df63"),
                            Age = 33,
                            Country = "Germany",
                            DriverName = "Sebastian Vettal",
                            Number = 5,
                            Team = "Aston Martin"
                        },
                        new
                        {
                            DriverId = new Guid("502daf0a-1d62-4246-80c9-8b7c298179cc"),
                            Age = 24,
                            Country = "France",
                            DriverName = "Esteban Ocon",
                            Number = 31,
                            Team = "Alpine"
                        },
                        new
                        {
                            DriverId = new Guid("895a6f97-49ee-43ed-94c8-9e2154b4a0aa"),
                            Age = 39,
                            Country = "Spain",
                            DriverName = "Fernando Alonso",
                            Number = 14,
                            Team = "Alpine"
                        },
                        new
                        {
                            DriverId = new Guid("7066bdfc-8de4-4e33-9b92-779f3412b470"),
                            Age = 41,
                            Country = "Finland",
                            DriverName = "Kimi Räikkönen",
                            Number = 7,
                            Team = "Alfa Romeo Racing"
                        },
                        new
                        {
                            DriverId = new Guid("4bad11ff-f791-455b-a2a2-e553c35e3a94"),
                            Age = 27,
                            Country = "Italy",
                            DriverName = "Antonio Giovinazzi",
                            Number = 99,
                            Team = "Alfa Romeo Racing"
                        },
                        new
                        {
                            DriverId = new Guid("2b6319db-f75e-4a86-b35c-5db6861a0e9d"),
                            Age = 25,
                            Country = "Canada",
                            DriverName = "Nicholas Latifi",
                            Number = 6,
                            Team = "Williams"
                        },
                        new
                        {
                            DriverId = new Guid("9cf30819-004a-4490-a906-f956ab6b7ed7"),
                            Age = 23,
                            Country = "United Kingdom",
                            DriverName = "Goerge Russel",
                            Number = 63,
                            Team = "Williams"
                        },
                        new
                        {
                            DriverId = new Guid("625617c7-1bca-4b83-b0bd-c3c9044ebf2b"),
                            Age = 22,
                            Country = "Germany",
                            DriverName = "Mick Schumacher",
                            Number = 47,
                            Team = "Haas F1 Team"
                        },
                        new
                        {
                            DriverId = new Guid("a56a648b-69d2-4e74-b01a-2c4ebd58374a"),
                            Age = 22,
                            Country = "Russia",
                            DriverName = "Nikita Mazepin",
                            Number = 9,
                            Team = "Haas F1 Team"
                        });
                });

            modelBuilder.Entity("Formula1.Models.DriverCircuits", b =>
                {
                    b.HasOne("Formula1.Models.Circuits", "Circuits")
                        .WithMany("DriversFavorite")
                        .HasForeignKey("CircuitsCircuitId");

                    b.HasOne("Formula1.Models.Drivers", "Driver")
                        .WithMany("FavoriteCircuits")
                        .HasForeignKey("DriverId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circuits");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Formula1.Models.Circuits", b =>
                {
                    b.Navigation("DriversFavorite");
                });

            modelBuilder.Entity("Formula1.Models.Drivers", b =>
                {
                    b.Navigation("FavoriteCircuits");
                });
#pragma warning restore 612, 618
        }
    }
}
