// <auto-generated />
using System;
using Formula1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Formula1.Migrations
{
    [DbContext(typeof(FormulaContext))]
    partial class FormulaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Formula1.Models.Circuits", b =>
                {
                    b.Property<Guid>("CircuitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CircuitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CircuitId");

                    b.ToTable("Circuits");

                    b.HasData(
                        new
                        {
                            CircuitId = new Guid("512f043b-eff1-4212-a64e-8be645f3370c"),
                            CircuitName = "Albert Park",
                            Country = "Australia",
                            Url = "https://f1-circuits.nl/albert-park/"
                        },
                        new
                        {
                            CircuitId = new Guid("ba4f4f0e-3784-49e2-a818-e24db49946bf"),
                            CircuitName = "Shanghai International Circuit",
                            Country = "China",
                            Url = "https://f1-circuits.nl/shanghai/"
                        },
                        new
                        {
                            CircuitId = new Guid("caeb4f4d-c75f-45df-9e62-ff170dfe7416"),
                            CircuitName = "Bahrain International Circuit",
                            Country = "Bahrain",
                            Url = "https://f1-circuits.nl/bahrain/"
                        },
                        new
                        {
                            CircuitId = new Guid("bb0c9daf-7b6a-456b-9048-c13f26c0c5d3"),
                            CircuitName = "Sochi Autodrom",
                            Country = "Russia",
                            Url = "https://f1-circuits.nl/sochi/"
                        },
                        new
                        {
                            CircuitId = new Guid("7142c5fe-2deb-4598-8d05-2060b76a0e8a"),
                            CircuitName = "Circuit de Barcelona-Catalunya",
                            Country = "Spain",
                            Url = "https://f1-circuits.nl/barcelona/"
                        },
                        new
                        {
                            CircuitId = new Guid("b3feaf99-b7e1-44c8-986b-121a1bb0aecd"),
                            CircuitName = "Circuit de Monaco",
                            Country = "Monaco",
                            Url = "https://f1-circuits.nl/monaco/"
                        },
                        new
                        {
                            CircuitId = new Guid("841aa539-eda8-4459-917a-81972f5cf7fe"),
                            CircuitName = "Circuit Gilles Villeneuve",
                            Country = "Canada",
                            Url = "https://f1-circuits.nl/gilles-villeneuve/"
                        },
                        new
                        {
                            CircuitId = new Guid("e1b16c4b-f1c3-4c4f-b5fc-b143da82e68e"),
                            CircuitName = "Baku City Circuit",
                            Country = "Azerbeidzjan",
                            Url = "https://f1-circuits.nl/baku/"
                        },
                        new
                        {
                            CircuitId = new Guid("2b611fb8-956a-4cc2-a880-6add6bbd22cb"),
                            CircuitName = "Red Bull Ring",
                            Country = "Austria",
                            Url = "https://f1-circuits.nl/red-bull-ring/"
                        },
                        new
                        {
                            CircuitId = new Guid("0294540b-5693-43f0-a31f-f715c0500c1b"),
                            CircuitName = "Silverstone",
                            Country = "United Kingdom",
                            Url = "https://f1-circuits.nl/silverstone/"
                        },
                        new
                        {
                            CircuitId = new Guid("64e3e378-5404-404d-8d9b-6911b83fdf98"),
                            CircuitName = "Hungaroring",
                            Country = "Hungary",
                            Url = "https://f1-circuits.nl/hungaroring/"
                        },
                        new
                        {
                            CircuitId = new Guid("2c149dfa-ee42-4be3-8680-3c214c02e021"),
                            CircuitName = "Circuit Spa-Francorchamps",
                            Country = "Belgium",
                            Url = "https://f1-circuits.nl/spa-francorchamps/"
                        },
                        new
                        {
                            CircuitId = new Guid("7781a9fd-d3d0-4d58-8738-99261407ae5f"),
                            CircuitName = "Autodromo Nazionale Monza",
                            Country = "Italy",
                            Url = "https://f1-circuits.nl/monza/"
                        },
                        new
                        {
                            CircuitId = new Guid("d11f4ac6-903b-49d3-801b-d943ccf80e05"),
                            CircuitName = "Marina Bay Circuit",
                            Country = "Singapore",
                            Url = "https://f1-circuits.nl/marina-bay/"
                        },
                        new
                        {
                            CircuitId = new Guid("8a928650-adbb-488c-90f8-9e70d03d1a8d"),
                            CircuitName = "Sepang International Circuit",
                            Country = "Malaysia",
                            Url = "https://f1-circuits.nl/sepang/"
                        },
                        new
                        {
                            CircuitId = new Guid("5ee892ee-85cb-4136-89e8-05f1d7a29fe2"),
                            CircuitName = "Suzuka",
                            Country = "Japan",
                            Url = "https://f1-circuits.nl/suzuka/"
                        },
                        new
                        {
                            CircuitId = new Guid("7d2fba07-1dd3-472c-a3b5-150b57573f79"),
                            CircuitName = "Autódromo Hermanos Rodríguez",
                            Country = "Mexico",
                            Url = "https://f1-circuits.nl/mexico/"
                        },
                        new
                        {
                            CircuitId = new Guid("cadee173-00ab-47a5-968e-4c464799ce5b"),
                            CircuitName = "Circuit of the Americas",
                            Country = "United States",
                            Url = "https://f1-circuits.nl/americas/"
                        },
                        new
                        {
                            CircuitId = new Guid("ac5f1475-95b4-4cf2-8416-cb0edf400e42"),
                            CircuitName = "Interlagos",
                            Country = "Brazil",
                            Url = "https://f1-circuits.nl/interlagos/"
                        },
                        new
                        {
                            CircuitId = new Guid("d16f3146-1523-4cd0-867d-935ad1da0a72"),
                            CircuitName = "Yas Marina Circuit",
                            Country = "United Arab Emirates",
                            Url = "https://f1-circuits.nl/yas-marina/"
                        },
                        new
                        {
                            CircuitId = new Guid("19c30281-ccae-475a-8b2b-e577f87f579c"),
                            CircuitName = "Paul Ricard",
                            Country = "France",
                            Url = "https://f1-circuits.nl/paul-ricard/"
                        },
                        new
                        {
                            CircuitId = new Guid("d3918ba4-ddc6-4b03-bc68-635ed3446b6d"),
                            CircuitName = "Hockendheimring",
                            Country = "Germany",
                            Url = "https://f1-circuits.nl/hockenheim/"
                        },
                        new
                        {
                            CircuitId = new Guid("64f974ab-c560-4a45-9d44-92c863472fa9"),
                            CircuitName = "Zandvoort",
                            Country = "The Netherlands",
                            Url = "https://f1-circuits.nl/zandvoort/"
                        },
                        new
                        {
                            CircuitId = new Guid("3ffdb7e6-b524-475a-9fb9-b9a7bac453df"),
                            CircuitName = "Vietnam",
                            Country = "Vietnam",
                            Url = "https://f1-circuits.nl/vietnam/"
                        },
                        new
                        {
                            CircuitId = new Guid("d326e22c-5626-4a0f-a5c9-6f17850e8297"),
                            CircuitName = "Mugello Circuit",
                            Country = "Italy",
                            Url = "https://f1-circuits.nl/mugello/"
                        },
                        new
                        {
                            CircuitId = new Guid("0fe30714-b913-48a1-9f61-53c91dcd4068"),
                            CircuitName = "Nürburging",
                            Country = "Germany",
                            Url = "https://f1-circuits.nl/nurburgring/"
                        },
                        new
                        {
                            CircuitId = new Guid("223830b1-adf8-4da1-a97b-78a6cdbd8fb9"),
                            CircuitName = "Autodromo Enzo e Dino Ferrari",
                            Country = "Italy",
                            Url = "https://f1-circuits.nl/imola/"
                        },
                        new
                        {
                            CircuitId = new Guid("7f0131fc-c2e2-49bf-af20-d23aebf0d32a"),
                            CircuitName = "Autodromo Internacional do Algarve",
                            Country = "Portugal",
                            Url = "https://f1-circuits.nl/algarve/"
                        },
                        new
                        {
                            CircuitId = new Guid("01061da6-b020-4b84-95b0-fc2b2c2a594f"),
                            CircuitName = "Istanbul Park",
                            Country = "Turkey",
                            Url = "https://f1-circuits.nl/istanbul-park/"
                        },
                        new
                        {
                            CircuitId = new Guid("99cd9ff8-2f0f-4599-9ab2-56912e9188d9"),
                            CircuitName = "Jeddah Street Circuit",
                            Country = "Saudi Arabia",
                            Url = "https://f1-circuits.nl/jeddah-street/"
                        });
                });

            modelBuilder.Entity("Formula1.Models.DriverCircuits", b =>
                {
                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("CircuitId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("CircuitsCircuitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DriverId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DriverId", "CircuitId");

                    b.HasIndex("CircuitsCircuitId");

                    b.HasIndex("DriverId1");

                    b.ToTable("DriverCircuits");
                });

            modelBuilder.Entity("Formula1.Models.Drivers", b =>
                {
                    b.Property<Guid>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Team")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriverId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            DriverId = new Guid("5f54c955-9110-4d3e-8f8d-3ca07557a703"),
                            Age = 23,
                            Country = "Netherlands",
                            DriverName = "Max Verstappen",
                            Number = 33,
                            Team = "Red Bull Racing"
                        },
                        new
                        {
                            DriverId = new Guid("1475975a-4e6a-4793-bf6f-693467ac1c7e"),
                            Age = 31,
                            Country = "Mexico",
                            DriverName = "Sergio Perez",
                            Number = 11,
                            Team = "Red Bull Racing"
                        },
                        new
                        {
                            DriverId = new Guid("595a5aa9-ea7c-4cdb-a177-0efe13606613"),
                            Age = 26,
                            Country = "Spain",
                            DriverName = "Carlos Sainz",
                            Number = 55,
                            Team = "Ferrari"
                        },
                        new
                        {
                            DriverId = new Guid("968c5f06-e290-4974-bf6c-37f6d1138c48"),
                            Age = 23,
                            Country = "Monaco",
                            DriverName = "Charles Leclerc",
                            Number = 16,
                            Team = "Ferrari"
                        },
                        new
                        {
                            DriverId = new Guid("e2e21b92-565c-48d3-b4d4-41fd7a531cc3"),
                            Age = 21,
                            Country = "United Kingdom",
                            DriverName = "Lando Norris",
                            Number = 4,
                            Team = "McLaren"
                        },
                        new
                        {
                            DriverId = new Guid("6a77e533-c922-40d2-a1ed-7386c397bc6b"),
                            Age = 31,
                            Country = "Australia",
                            DriverName = "Daniel Ricciardo",
                            Number = 3,
                            Team = "McLaren"
                        },
                        new
                        {
                            DriverId = new Guid("e8507f68-8de4-4ea6-b92e-d91b0543011a"),
                            Age = 36,
                            Country = "United Kingdom",
                            DriverName = "Lewis Hamilton",
                            Number = 44,
                            Team = "Mercedes"
                        },
                        new
                        {
                            DriverId = new Guid("2b6d4d52-020b-44bd-8788-38563ef4596a"),
                            Age = 31,
                            Country = "Finland",
                            DriverName = "Valtteri Bottas",
                            Number = 77,
                            Team = "Mercedes"
                        },
                        new
                        {
                            DriverId = new Guid("1db5c575-8012-4faa-a8c9-3020e135417f"),
                            Age = 25,
                            Country = "France",
                            DriverName = "Pierre Gasly",
                            Number = 10,
                            Team = "AlphaTauri"
                        },
                        new
                        {
                            DriverId = new Guid("2fd42911-f406-48bf-9bbb-81fd631f0985"),
                            Age = 20,
                            Country = "Japan",
                            DriverName = "Yuki Tsunoda",
                            Number = 22,
                            Team = "AlphaTauri"
                        },
                        new
                        {
                            DriverId = new Guid("37ea7987-ad52-4a08-bf75-82dd83c3cd99"),
                            Age = 25,
                            Country = "France",
                            DriverName = "Lance Stroll",
                            Number = 18,
                            Team = "Aston Martin"
                        },
                        new
                        {
                            DriverId = new Guid("dc81fcb2-8193-40f6-91d0-42932d29850e"),
                            Age = 33,
                            Country = "Germany",
                            DriverName = "Sebastian Vettal",
                            Number = 5,
                            Team = "Aston Martin"
                        },
                        new
                        {
                            DriverId = new Guid("0055056e-7764-4c5a-9248-803401007231"),
                            Age = 24,
                            Country = "France",
                            DriverName = "Esteban Ocon",
                            Number = 31,
                            Team = "Alpine"
                        },
                        new
                        {
                            DriverId = new Guid("c73010f7-2432-4e85-9c71-29b68c0dbd5c"),
                            Age = 39,
                            Country = "Spain",
                            DriverName = "Fernando Alonso",
                            Number = 14,
                            Team = "Alpine"
                        },
                        new
                        {
                            DriverId = new Guid("315a121a-d76a-4052-9564-d3e1f7909407"),
                            Age = 41,
                            Country = "Finland",
                            DriverName = "Kimi Räikkönen",
                            Number = 7,
                            Team = "Alfa Romeo Racing"
                        },
                        new
                        {
                            DriverId = new Guid("f7138146-088b-4cba-a929-4cbd748d5bc8"),
                            Age = 27,
                            Country = "Italy",
                            DriverName = "Antonio Giovinazzi",
                            Number = 99,
                            Team = "Alfa Romeo Racing"
                        },
                        new
                        {
                            DriverId = new Guid("e8441d3c-a7a1-4c31-94df-2c3cc5cbe72e"),
                            Age = 25,
                            Country = "Canada",
                            DriverName = "Nicholas Latifi",
                            Number = 6,
                            Team = "Williams"
                        },
                        new
                        {
                            DriverId = new Guid("a8bd142a-e491-4206-b08d-5c170400b018"),
                            Age = 23,
                            Country = "United Kingdom",
                            DriverName = "Goerge Russel",
                            Number = 63,
                            Team = "Williams"
                        },
                        new
                        {
                            DriverId = new Guid("45910462-6ed5-4e05-8aff-aafb1c6f1463"),
                            Age = 22,
                            Country = "Germany",
                            DriverName = "Mick Schumacher",
                            Number = 47,
                            Team = "Haas F1 Team"
                        },
                        new
                        {
                            DriverId = new Guid("c5618bef-b2d2-4a21-9598-d6277e8d5391"),
                            Age = 22,
                            Country = "Russia",
                            DriverName = "Nikita Mazepin",
                            Number = 9,
                            Team = "Haas F1 Team"
                        });
                });

            modelBuilder.Entity("Formula1.Models.Ranking", b =>
                {
                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("DriverNameDriverId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Place");

                    b.HasIndex("DriverNameDriverId");

                    b.ToTable("Ranking");
                });

            modelBuilder.Entity("Formula1.Models.TeamDrivers", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<Guid?>("DriverId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TeamsTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TeamId", "DriverId");

                    b.HasIndex("DriverId1");

                    b.HasIndex("TeamsTeamId");

                    b.ToTable("TeamDrivers");
                });

            modelBuilder.Entity("Formula1.Models.Teams", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = new Guid("34183c20-6065-49b7-8fee-072ba7e5f9ba"),
                            TeamName = "Redd Bull Racing"
                        },
                        new
                        {
                            TeamId = new Guid("43d19cab-ac94-4b7a-b7d3-bf9652037fc4"),
                            TeamName = "Ferrari"
                        },
                        new
                        {
                            TeamId = new Guid("4808955a-16b7-4116-bdd9-264e60adc570"),
                            TeamName = "Mercedes"
                        },
                        new
                        {
                            TeamId = new Guid("34220ca2-1207-4026-9422-17b111a8d13d"),
                            TeamName = "McLaren"
                        },
                        new
                        {
                            TeamId = new Guid("ce6a59f8-28fc-45e9-82c9-2bb5c422ed37"),
                            TeamName = "Haas F1 Team"
                        },
                        new
                        {
                            TeamId = new Guid("6c7a8678-de8f-4540-b5af-7cc17f47e653"),
                            TeamName = "Williams"
                        },
                        new
                        {
                            TeamId = new Guid("76bd5e3a-75d7-4ff5-8c93-12e947fd1694"),
                            TeamName = "AlphaTauri"
                        },
                        new
                        {
                            TeamId = new Guid("cf0b9681-e396-4af2-924e-8271212e37e6"),
                            TeamName = "Alpine"
                        },
                        new
                        {
                            TeamId = new Guid("14b954a5-3d71-4c5d-839d-75d35c8a8ca6"),
                            TeamName = "Alfa Romeo Racing"
                        },
                        new
                        {
                            TeamId = new Guid("51321c7f-b5f9-41dc-9472-e2c4b5e5c01c"),
                            TeamName = "Aston Martin"
                        });
                });

            modelBuilder.Entity("Formula1.Models.DriverCircuits", b =>
                {
                    b.HasOne("Formula1.Models.Circuits", "Circuits")
                        .WithMany("DriversFavorite")
                        .HasForeignKey("CircuitsCircuitId");

                    b.HasOne("Formula1.Models.Drivers", "Driver")
                        .WithMany("FavoriteCircuits")
                        .HasForeignKey("DriverId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circuits");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Formula1.Models.Ranking", b =>
                {
                    b.HasOne("Formula1.Models.Drivers", "DriverName")
                        .WithMany()
                        .HasForeignKey("DriverNameDriverId");

                    b.Navigation("DriverName");
                });

            modelBuilder.Entity("Formula1.Models.TeamDrivers", b =>
                {
                    b.HasOne("Formula1.Models.Drivers", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId1");

                    b.HasOne("Formula1.Models.Teams", "Teams")
                        .WithMany("Drivers")
                        .HasForeignKey("TeamsTeamId");

                    b.Navigation("Driver");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Formula1.Models.Circuits", b =>
                {
                    b.Navigation("DriversFavorite");
                });

            modelBuilder.Entity("Formula1.Models.Drivers", b =>
                {
                    b.Navigation("FavoriteCircuits");
                });

            modelBuilder.Entity("Formula1.Models.Teams", b =>
                {
                    b.Navigation("Drivers");
                });
#pragma warning restore 612, 618
        }
    }
}
